backend:
  name: github
  repo: kooku94/kooku-s-log

media_folder: public/assets
public_folder: /assets

collections:
  - name: posts
    label: Posts
    folder: content/blog/etc
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: category, label: Category }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
